//------------------------------------------------------------------------------
// <auto-generated>
//     если использовать тег copyright то появляются ошибки. пока что не разобрался как это исправить
// </auto-generated>
//------------------------------------------------------------------------------
namespace HW10_Threads_Cyc
{
    /// <summary>
    /// Класс для тестирования параметров MaxThreads и MinThreads.
    /// </summary>
    internal class Program
    {
        private const int Delay = 10000;
        private const int Iterations = 1000;
        private const int MaxThreads = 10000;
        private const int MinThreads = 1;

        /// <summary>
        /// Точка входа в программу.
        /// </summary>
        /// <param name="args">Аргументы командной строки.</param>
        public static void Main(string[] args)
        {
            ThreadPool.SetMinThreads(MinThreads, 1000);
            ThreadPool.SetMaxThreads(MaxThreads, 1000);
            for (int i = 0; i < Iterations; i++)
            {
                ThreadPool.QueueUserWorkItem(ThreadPrintInfo, i);
            }

            Console.ReadKey();
        }

        /// <summary>
        /// вывод информации о текущем потоке.
        /// </summary>
        /// <param name="state">текущая итерация.</param>
        public static void ThreadPrintInfo(object state)
        {
            Console.WriteLine($"Iteration: {state}, Thread count: {ThreadPool.ThreadCount}");
            Thread.Sleep(Delay);

            // Console.WriteLine($"Iteration: {state}, Thread done!");
        }
    }
}
